PeaceCraftFun/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pcf.urls'), name='pcf'),
    path('accounts/', include('allauth.urls'), name='accounts'),
    path('api/', include('api.urls'), name='api'),
]


handler403 = 'pcf.views.permission_denied_view'
handler404 = 'pcf.views.page_not_found_view'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path, include
from requests import delete

from .views import *
from .routers import post_router

app_name = 'api'

urlpatterns = [
    # path('v1/post_list/', PostListAPIView.as_view()),
    # path('v1/post/<int:pk>/', PostSingleView.as_view()),
    # path('v1/post/', PostViewSet.as_view({'get': 'list'})),
    # path('v1/post/<int:pk>', PostViewSet.as_view({'get': 'retrieve'})),
    # path('v1/post/', PostViewSet.as_view({'post': 'create'})),
    path('v1/', include(post_router.urls)),
    path('v1/subscribe/', subscribe),
    path('v1/unsubscribe/', unsubscribe),
    path('v1/personal_page/', PersonalPageView.as_view()),
    path('v1/post/<int:post_id>/add_comment/', CommentAddAPIView.as_view()),
]

pcf/urls.py
from django.urls import path

from pcf.views import *

urlpatterns = [
    path('', AdsListView.as_view(), name='home'),
    path('<int:pk>/', AdDetailView.as_view(), name='post'),
    path('verify_email/', VerifyEmailView.as_view(), name='verify_email'),
    path('resend_code/', email_resend, name='resend_code'),
    path('post_add/', AdCreateView.as_view(), name='post_add'),
    path('<int:pk>/add_comment/', add_comment, name='add_comment'),
    path('<int:pk>/post_update/', AdUpdateView.as_view(), name='post_update'),
    path('news/', NewsCreationView.as_view(), name='news'),
    path('unsubscribe/', unsubscribe, name='unsubscribe'),
    path('subscribe/', subscribe, name='subscribe'),
    path('personal_page/', PersonalPageView.as_view(), name='personal_page'),
    path('<int:pk>/accept_comment/', accept_comment, name='accept_comment'),
    path('<int:pk>/delete_comment/', delete_comment, name='delete_comment'),
]

pcf/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from django.urls import reverse_lazy
from django.core.cache import cache


class Post(models.Model):
    CATEGORY_CHOICES = [
        ('TA', 'Танки'), ('HE', 'Хилы'), ('DD', 'ДД'), ('ME', 'Торговцы'),
        ('GM', 'Гилдмастеры'),('QG', 'Квестгиверы'), ('BS', 'Кузнецы'),
        ('TA', 'Кожевники'), ('PM', 'Зельевары'), ('SM', 'Мастера Заклинаний')
    ]
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.CharField(max_length=2, choices=CATEGORY_CHOICES)
    title = models.CharField(max_length=255)
    content = RichTextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy('post', kwargs={'pk': self.id})

    def save(self, *args, **kwargs):
        cache.delete('post_list')
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        cache.delete('post_list')
        super().delete(*args, **kwargs)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    accepted = models.BooleanField(default=False)

    def __str__(self):
        return self.text[:50]


class OneTimeCode(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    code = models.IntegerField()

    def __str__(self):
        return f'{self.user}: {self.code}'

pcf/forms.py
from django import forms
from allauth.account.forms import SignupForm
from django.contrib.auth.models import Group
from ckeditor.widgets import CKEditorWidget
from ckeditor.fields import RichTextFormField

from .models import Post, OneTimeCode, Comment


class CustomSignupForm(SignupForm):
    subscribe = forms.BooleanField(label='Подписаться на новостную рассылку',
                                   required=False,
                                   widget=forms.CheckboxInput(attrs={'class': 'form-check-input',
                                                              'type': 'checkbox'}))

    field_order = ['username', 'email', 'password1', 'password2', 'subscribe']

    def save(self, request):
        user = super(CustomSignupForm, self).save(request)
        if self.cleaned_data['subscribe']:
            subscribed_group = Group.objects.get(name='subscribed_users')
            subscribed_group.user_set.add(user)

        return user


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['category', 'title', 'content']
        labels = {
            'category': 'Выберите категорию',
            'title': '',
            'content': ''
        }

        widgets = {
            'content': CKEditorWidget(),
            'category': forms.Select(attrs={'class': 'form-select form-select-sm mx-auto my-3',
                                            'style': 'max-width:200px'}),
            'title': forms.TextInput(attrs={'class': 'form-control mx-auto my-4',
                                            'style': 'max-width:500px',
                                            'placeholder': 'Введите заголовок...'})
        }


class VerifyEmailForm(forms.ModelForm):
    """Form for verifying email with OTC"""

    class Meta:
        model = OneTimeCode
        fields = ['code']
        labels = {'code': 'Введите код из письма'}

        widgets = {
            'code': forms.TextInput(attrs={'class': 'form-control'})
        }


class CommentForm(forms.ModelForm):
    """Form for creating new comments"""

    class Meta:
        model = Comment
        fields = ['text']


class NewsForm(forms.Form):
    """Form for notification emails"""

    subject = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'class': 'form-control mx-auto',
                                                                            'placeholder': 'Введите тему письма',
                                                                            'style': 'max-width:500px'}))
    content = RichTextFormField()

pcf/views.py
import datetime
import pytz
from random import choice

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, FormView, UpdateView
from django.contrib.auth.models import Group
from django.http import HttpResponseRedirect, JsonResponse
from django.core.cache import cache

from env import TZ
from .filters import CommentFilter
from .models import Post, OneTimeCode, Comment
from .forms import VerifyEmailForm, PostForm, CommentForm,NewsForm
from .tasks import resend_verification_code
from .utils import codes, menu, send_news_to_subscribers


class AdsListView(ListView):
    """Main page view, list of posts """

    template_name = 'pcf/postList.html'
    queryset = Post.objects.order_by('-created_at').annotate(comments_count=Count('comments')).select_related('author')
    context_object_name = 'posts'
    extra_context = {'menu': menu}
    paginate_by = 10

    def get_queryset(self):
        queryset = cache.get('post_list', None)

        if not queryset:
            queryset = Post.objects.order_by('-created_at').annotate(comments_count=Count('comments')).select_related('author')
            cache.set('post_list', queryset)

        return queryset


class AdDetailView(DetailView):
    """Post detail view with its content and comments"""

    model = Post
    template_name = 'pcf/postDetails.html'
    context_object_name = 'post'
    extra_context = {'menu': menu}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.object
        comments = post.comments.all().select_related('author')
        context['comments'] = comments
        return context


class AdCreateView(LoginRequiredMixin, CreateView):
    """Post create view"""

    form_class = PostForm
    template_name = 'pcf/postAdd.html'
    extra_context = {'menu': menu}
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        user = self.request.user
        form.instance.author = user
        response = super().form_valid(form)

        return response


class AdUpdateView(LoginRequiredMixin, UpdateView):
    """Updates existing post (only for its author)"""

    model = Post
    template_name = 'pcf/postAdd.html'
    form_class = PostForm
    extra_context = {'menu': menu}

    def dispatch(self, request, *args, **kwargs):
        post = self.get_object()
        if post.author != request.user:
            raise PermissionDenied('Только автор объявления может его редактировать.')
        return super().dispatch(request, *args, **kwargs)


class PersonalPageView(LoginRequiredMixin, ListView):
    """Personal page for registered and verified users
    with all the comments from all users posts"""

    model = Comment
    template_name = 'pcf/personalPage.html'
    context_object_name = 'comments'
    extra_context = {'menu': menu}

    def get_queryset(self):
        queryset = Comment.objects.filter(post__author=self.request.user).order_by('-created_at').select_related('author')
        self.comment_filter = CommentFilter(self.request.GET or None, user=self.request.user, queryset=queryset)
        return self.comment_filter.qs


class VerifyEmailView(FormView):
    """Email Verification with OTC created on user signup.
    If user doesn't verify email within 24 hours - users
    account will be deleted."""

    template_name = 'pcf/verifyEmail.html'
    form_class = VerifyEmailForm
    success_url = reverse_lazy('home')
    extra_context = {'menu': [{'title': 'Выход', 'url_name': 'account_logout'}]}

    def dispatch(self, request, *args, **kwargs):
        if request.user.groups.filter(name='verified_users').exists() or not request.user.is_authenticated:
            return HttpResponseRedirect(reverse_lazy('home'))
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        user = self.request.user
        code_object = OneTimeCode.objects.get(user=user)
        if code_object.code == form.instance.code:
            user.groups.add(Group.objects.get(name='verified_users'))
            code_object.delete()
            return super().form_valid(form)
        else:
            form.add_error(None, 'Неправильный код')
            return super().form_invalid(form)


class NewsCreationView(FormView):
    """Creates emails for subscribed users.
    Available for staff only"""

    template_name = 'pcf/news.html'
    form_class = NewsForm
    extra_context = {'menu': menu}
    success_url = reverse_lazy('home')

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_staff:
            raise PermissionDenied('Только админы могут рассылать новости')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        send_news_to_subscribers(form.cleaned_data['subject'], form.cleaned_data['content'])
        return super().form_valid(form)


@login_required
def email_resend(request, *args, **kwargs):
    """Resending email for verification with OTC with
     deleting previous one"""

    user = request.user
    timezone = pytz.timezone(TZ)
    time_left = str(user.date_joined + datetime.timedelta(days=1) - datetime.datetime.now(timezone)).split('.')[0]
    OneTimeCode.objects.get(user=user).delete()
    code = OneTimeCode.objects.create(user=user, code=choice(codes))
    resend_verification_code.apply_async(args=[code.code, user.email, time_left])
    return redirect('verify_email')


@login_required
def add_comment(request, pk):
    """Add comment to posts"""

    post = get_object_or_404(Post, pk=pk)
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.author = request.user
        comment.save()
    return redirect('post', pk)


@login_required
def unsubscribe(request):
    """Email notifications unsubscribe"""

    if request.user.groups.filter(name='subscribed_users').exists():
        group = Group.objects.get(name='subscribed_users')
        group.user_set.remove(request.user)
        return render(request, 'pcf/message.html', context={'title': 'Отписка',
                                                            'message': 'Вы отписались от новостной рассылки.',
                                                            'menu': menu})
    else:
        return redirect('home')


@login_required
def subscribe(request):
    """Subscription to email notifications"""

    if not request.user.groups.filter(name='subscribed_users').exists():
        group = Group.objects.get(name='subscribed_users')
        group.user_set.add(request.user)
        return render(request, 'pcf/message.html', context={'title': 'Подписка',
                                                            'message': 'Вы подписались на новостную рассылку.',
                                                            'menu': menu})
    else:
        return redirect('home')


@login_required
def accept_comment(request, pk):
    """Comment acception by post author"""

    comment = Comment.objects.get(pk=pk)
    if comment.post.author != request.user:
        raise PermissionDenied('Принять отклик может только автор объявления, '
                               'под которым он было написан.')
    if not comment.accepted:
        comment.accepted = True
        comment.save()
    return JsonResponse({'accepted': True})


@login_required
def delete_comment(request, pk):
    """Comment deletion by post author"""

    comment = Comment.objects.get(pk=pk)
    if comment.post.author != request.user:
        raise PermissionDenied('Удалить отклик может только автор объявления, '
                               'под которым он было написан.')
    comment.delete()
    return JsonResponse({'deleted': True})


def permission_denied_view(request, exception=None):
    """403 handler"""

    context = {'message': str(exception), 'menu': menu}
    return render(request, '403.html', context=context, status=403)


def page_not_found_view(request, exception=None):
    """404 handler"""

    context = {'message': str(exception), 'menu': menu}
    return render(request, '404.html', context=context, status=404)

pcf/templates/pcf/default.html
{% load static %}
{% load pcf.custom_filters %}
{% load cache %}

<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content="Simple NewsPaper Site on Django 4.1.7"/>
    <meta name="author" content="OneHandedPirate"/>
    <title>{% block title %}{% endblock title %} - PeaceCraftFun</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href={% static "pcf/assets/favicon.ico" %} />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href={% static 'pcf/css/styles.css' %} rel="stylesheet"/>
    <script src="https://kit.fontawesome.com/32d5dc53de.js" crossorigin="anonymous"></script>
    {% block head %}{% endblock %}
</head>

<body class="d-flex flex-column h-100" style="background-image: url({% static 'pcf/assets/site_bd2.jpg' %}); background-size: cover; background-position: center center; background-repeat: no-repeat; background-attachment: fixed;">
{% with is_authenticated=request.user.is_authenticated is_subscribed=request.user|is_subscribed %}
    <!-- Responsive navbar-->
    <nav class="navbar navbar-expand-lg navbar-light bg-warning">
    <div class="container-fluid col-11 col-lg-10 col-xl-12" style="max-width: 1200px">
        <span>
            <a class="navbar-brand fw-bold" href="{% url 'home' %}">PeaceCraftFun</a>
            {% if is_authenticated %}
                |
                {{ user }}
            {% endif %}
        </span>
        {% if menu %}
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0 text-center">
                    {% for item in menu %}
                        {% if item.url_name == request.resolver_match.url_name %}
                            <li class="nav-item"><span class="nav-link active"
                                                       aria-current="page"><strong>{{ item.title }}</strong></span></li>
                        {% elif item.title == 'Вход' %}
                            {% if not is_authenticated %}
                                <li class="nav-item"><a class="nav-link" aria-current="page"
                                                        href="{% url 'account_login' %}">{{ item.title }}</a></li>
                            {% endif %}
                        {% elif item.title == 'Выход' %}
                            {% if is_authenticated %}
                                <li class="nav-item"><a class="nav-link" aria-current="page" data-bs-toggle="modal"
                                                        data-bs-target="#logoutModal"
                                                        style="cursor: pointer">{{ item.title }}</a></li>
                            {% endif %}
                        {% elif item.title == 'Добавить' %}
                            {% if is_authenticated %}
                                <li class="nav-item"><a class="nav-link" aria-current="page"
                                                        href='{% url item.url_name %}'
                                                        title="Добавить объявление">{{ item.title }}</a></li>
                            {% endif %}
                        {% elif item.title == 'Рассылка' %}
                            {% if user.is_staff %}
                                <li class="nav-item"><a class="nav-link" aria-current="page"
                                                        href='{% url item.url_name %}'>{{ item.title }}</a></li>
                            {% else %}
                            {% endif %}
                        {% elif item.title == 'Подписаться' %}
                            {% if is_authenticated %}
                                {% if not is_subscribed %}
                                    <li class="nav-item"><a class="nav-link"
                                                    href="{% url 'subscribe' %}"
                                                    title="Подписаться на новостную рассылку">Подписаться</a></li>
                                {% endif %}
                            {% endif %}
                        {% elif item.title == 'Отписаться'%}
                            {% if is_authenticated %}
                                {% if is_subscribed %}
                                    <li class="nav-item"><a class="nav-link"
                                                    href="{% url 'unsubscribe' %}"
                                                    title="Отписаться от новостной рассылки">Отписаться</a></li>
                                {% endif %}
                            {% endif %}
                        {% elif item.title == 'Личка' %}
                            {% if is_authenticated %}
                                <li class="nav-item"><a class="nav-link" aria-current="page"
                                                        href='{% url item.url_name %}'
                                                        title="Страница с откликами на ваши объявления">
                                    {{ item.title }}</a></li>
                            {% endif %}
                        {% else %}
                            {% if item.url_name %}
                                <li class="nav-item"><a class="nav-link" aria-current="page"
                                                        href='{% url item.url_name %}'>{{ item.title }}</a></li>
                            {% else %}
                                <li class="nav-item"><a class="nav-link" aria-current="page"
                                                        href=''>{{ item.title }}</a></li>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
    </div>
</nav>

<!-- Page content-->
<div class="container-fluid">
    <div class="text-center mx-auto container-fluid" style="max-width: 1200px">
        {% block content %}
        {% endblock content %}
    </div>
</div>

<!-- Pagination-->
{% if is_paginated %}
    {% include 'pcf/pagination.html' %}
{% endif %}

<!-- Footer-->
{% cache 3600 footer %}
<footer class="bg-warning mt-auto">
    <div class="row text-dark p-3 col-sm-12 col-md-10 mx-auto" style="max-width: 1200px">
        <div class="text-start col-8">
            <p>© 2023 PeaceCraftFun</p>
        </div>
        <div class="text-end col-4 ">
            <a class="fa-brands fa-github fa-2xl m-1 text-decoration-none"
               href="https://github.com/OneHandedPirate" style="height:25px" target="_blank"></a>
            <a class="fa-brands fa-vk fa-2xl m-1 text-decoration-none" href="https://vk.com/onehandedpirate"
               style="height:25px" target="_blank"></a>
            <a class="fa-brands fa-reddit fa-2xl m-1 text-decoration-none" style="height:25px"
               href="https://www.reddit.com/user/OneHandedPirateMKII" target="_blank"></a>
        </div>
    </div>
</footer>
{% endcache %}

<!-- Logout Modal -->
{% if is_authenticated %}
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="logoutModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header bg-warning">
                    <h5 class="modal-title" id="logoutModalLabel">Выход с сайта</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body text-center">
                    <p>Уверены в своем решении?</p>
                </div>
                <div class="modal-footer justify-content-center">
                    <button type="button" class="btn btn-warning" data-bs-dismiss="modal">Остаться на сайте</button>
                    <form method="post" action="{% url 'account_logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Выйти</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endif %}
{% if is_authenticated and not is_subscribed and request.path != '/verify_email/' %}
    <a href="{% url 'subscribe' %}" class="circular-button inner-shadow overflow-hidden" title="Подписаться на новостную рассылку"><i class="fa-solid fa-bell"></i></a>
{% elif is_authenticated and is_subscribed and request.path != '/verify_email/' %}
    <a href="{% url 'unsubscribe' %}" class="circular-button inner-shadow overflow-hidden" title="Отписаться от новостной рассылки"><i class="fa-solid fa-ban"></i></a>
{% endif %}

<!-- JS-->
<script>const csrfToken = `{{ csrf_token }}`</script>
<script src="{% static 'pcf/js/bootstrap.bundle.min.js' %}"></script>
{% if is_authenticated and not is_subscribed and request.path != '/verify_email/' %}
    <script>
        let subscription_button = document.querySelector('.circular-button')
        console.log(subscription_button)
        subscription_button.addEventListener('mouseover', (event) => {
            subscription_button.innerHTML = 'Подписаться'
        })
        subscription_button.addEventListener('mouseout', (event) => {
            subscription_button.innerHTML = '<i class="fa-solid fa-bell"></i>'
        })
    </script>
{% elif is_authenticated and is_subscribed and request.path != '/verify_email/' %}
    <script>
        let subscription_button = document.querySelector('.circular-button')
        console.log(subscription_button)
        subscription_button.addEventListener('mouseover', (event) => {
            subscription_button.innerHTML = 'Отписаться'
        })
        subscription_button.addEventListener('mouseout', (event) => {
            subscription_button.innerHTML = '<i class="fa-solid fa-ban"></i>'
        })
    </script>
{% endif %}
{% endwith %}
</body>
</html>

pcf/templates/pcf/message.html
{% extends 'pcf/default.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h1 class="text-light my-3">{{ title }}</h1>
    <div class="container-fluid rounded-5 inner-shadow my-4 col-12 col-ls-8 bg-light pt-4 pb-1">
        <p>{{ message }}</p>
    </div>
{% endblock %}

pcf/templates/pcf/news.html
{% extends 'pcf/default.html' %}

{% block title %}Создание новости для рассылки{% endblock %}

{% block content %}
    <h1 class="my-3 text-light">Создание новости для рассылки</h1>
    <div class="container-fluid rounded-5 inner-shadow py-4 my-4 col-12 col-ls-8 bg-light bg-gradient"
     style="max-width: 900px">
        <form method="post">
            {% csrf_token %}
            {{ form.media }}
            {% for f in form %}
                <div class="my-4">{{ f }}</div>
            {% endfor %}
            <button type="submit" class="btn btn-warning my-3">
                Разослать
            </button>
        </form>
    </div>
{% endblock %}

pcf/templates/pcf/postDetails.html
{% extends 'pcf/default.html' %}

{% block title %}{{ post.title }}{% endblock %}


{% block content %}
    <div class="bg-light inner-shadow rounded-5 my-4 overflow-hidden">
        <div class="d-flex justify-content-between py-2 px-5 bg-warning inner-shadow">
            <span><strong>{{ post.author }}</strong></span>
            <span>Категория: <strong>{{ post.get_category_display }}</strong></span>
            <span>{{ post.created_at|date:"d.m.Y H:i" }}</span>
        </div>
        <hr class="m-0">
        <div class="pb-3 px-5">
            <h1 class="mt-3 mb-4">{{ post.title }}</h1>
            <div class="text-start">{{ post.content|safe }}</div>
        </div>
        <div>
            {% if post.author == user %}
                    <a class="btn btn-warning mt-3 mb-3" href="{% url 'post_update' post.pk %}">Редактировать пост</a>
                {% endif %}
            {% if post.updated_at|date:"d.m.Y H:i" != post.created_at|date:"d.m.Y H:i" %}
                <p>Изменено: {{ post.updated_at|date:"d.m.Y H:i" }}</p>
            {% endif %}
        </div>
    </div>

    {% if is_authenticated %}
        <button class="btn btn-warning mb-4 mt-3 shadow" data-bs-toggle="modal" data-bs-target="#addComment">
            Добавить отклик
        </button>

        <div class="modal fade" id="addComment" tabindex="-1" aria-labelledby="addCommentModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header bg-warning">
                        <label for="commentText" class="modal-title fs-5" id="addCommentModalLabel">Добавить отклик</label>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <form method="post" action="{% url 'add_comment' post.pk %}" id="addCommentForm">
                        {% csrf_token %}
                        <div class="modal-body">
                            <textarea type="text" name="text" id="commentText" class="form-control"
                                      style="min-height: 150px;" required
                                      placeholder="Введите текст..."></textarea>
                        </div>
                        <div class="modal-footer justify-content-center">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
                            <button type="submit" class="btn btn-warning" id="confirm-add" data-bs-dismiss="modal">
                                Добавить
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    {% endif %}

    {% if comments %}
        <h3 class="text-light mt-3">Отклики</h3>
        <ul class="list-unstyled mt-4 mb-5">
            {% for comment in comments|slice:'::-1' %}
                <li class="inner-shadow my-4 bg-light border border-dark border-1 rounded-5 mx-auto overflow-hidden" style="max-width: 500px">
                    <div class="text-center {% if not comment.accepted %}bg-warning{% else %}bg-success{% endif %} inner-shadow d-flex justify-content-between">
                        <span class="py-2 px-4"><strong>{{ comment.author }}</strong></span>
                        <span class="py-2 px-4">{{ comment.created_at|date:"d.m.Y H:i" }}</span>
                    </div>
                    <div class="py-3">
                        {{ comment.text }}
                    </div>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

pcf/templates/pcf/postInList.html
<div class="container-fluid rounded-5 inner-shadow my-4 col-12 col-ls-8 bg-light overflow-hidden"
     style="max-width: 1000px">
    <div class="row justify-content-between">
        <div class="d-flex justify-content-between py-1 px-3 px-md-5 bg-warning inner-shadow">
            <span>Автор: <strong>{{ post.author }}</strong></span>
            <span>{{ post.created_at }}</span>
        </div>
        <hr class="m-0">
        <a href="{% url 'post' post.pk %}" class="text-decoration-none link-dark" title="Нажмите, чтобы перейти к объявлению">
            <div class="text-center col-12 my-3">
                <h2>{{ post.title }}</h2>
            </div>
        </a>
        <hr class="m-0">
        <div class="d-flex justify-content-between py-1 px-3 px-md-5">
            <span>Откликов: {{ post.comments_count }}</span>
            <span>Категория: <strong>{{ post.get_category_display }}</strong></span>
            {{ request.user.email.verified }}
        </div>
    </div>
</div>

pcf/templates/pcf/postList.html
{% extends 'pcf/default.html' %}

{% block title %}Главная страница{% endblock %}

{% block content %}
    {% for post in posts %}
        {% include 'pcf/postInList.html' %}
    {% endfor %}
{% endblock %}